language: rust
cache: cargo
rust:
  - nightly
before_script:
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo test --verbose --all
